version: 2.1
jobs:
  build:
    machine: true
    steps:
      - run: |
          ssh -V
      - checkout

workflows:
  # Name the workflow "welcome"
  welcome:
    jobs:
      - build:
          pre-steps:
            - run:
                name: Install OpenSSH 8.1p1
                command: |
                    sudo apt-get update
                    mkdir ~/tempdownload; cd ~/tempdownload; wget https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-8.1p1.tar.gz; tar zxvf openssh-8.1p1.tar.gz; cd openssh-8.1p1 && ./configure && make && sudo make install
      
