version: 2.1
orbs:
  welcome-orb: circleci/welcome-orb@0.4.1

workflows:
  # Name the workflow "welcome"
  welcome:
    jobs:
      - welcome-orb/run:
          pre-steps:
            - checkout
                
          post-steps:
            - run:
                command: |
                  echo "GLOBAL UPDATE easy-peasy.... not"
