version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - run: |
          ssh -V
      - checkout

workflows:
  # Name the workflow "welcome"
  welcome:
    jobs:
      - build
